# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tuneZ' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tuneZ


  target 'tuneZTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tuneZUITests' do
    # Pods for testing
  end

end
